### ISSUE TITLE
Successfully installed UNKNOWN

### ISSUE THREAD

**Issue by nikosT** [gesape/AutoStatsQ#1]
Hi,

When I was trying to install it by the command:
```bash
sudo -H pip install master.zip
```

I got the following output:
```bash
Processing ./master.zip
Installing collected packages: UNKNOWN
  Running setup.py install for UNKNOWN ... done
Successfully installed UNKNOWN-0.1
```

**Comment by gesape** [comment]
Hi, I updated the instructions for downloading and installation. Please let me know if it works when you follow those?

**Comment by nikosT** [comment]
Hi, 
It still shows the package with the name UNKNOWN, but the autostatsq command works!

**Comment by nikosT** [comment]
Is it supported by Python 2.7?

**Comment by gesape** [comment]
I haven't tried Python 2.7, I am always using python 3.5.... so I guess there might be some problems.

**Comment by gesape** [comment]
Sorry for the late reply. I didn't know how to fix the unknown package name, but turned out it was very simple. Is fixed in the current version.
