### ISSUE TITLE
project linting 

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [gesape/AutoStatsQ#10]
Hey Gesa,

I recommend throwing `black` at autostatsq. It helps to maintain a consistent style which in turn helps others to quickly dive into your code.

Also I think the `dist` folder can be removed.

**Comment by HerrMuellerluedenscheid** [comment]
#11

**Comment by gesape** [comment]
...months ago since your comment and I still didn't get to that. But I think your pull request is so far from the current main branch, I should redo that at some time. Will keep this issue open until then.
