### ISSUE TITLE
Step-by-Step issue

### ISSUE THREAD

**Issue by bosby74** [gesape/AutoStatsQ#37]
Hi,
 I've installed the AutoStatQ software and I'm trying to follow the step-by-step example in the instruction pdf. 
Following Step 1, regarding the Catalog generation, and running 

autostatsq --config ./AutoStatsQ_settings.config --run -l INFO

I find this output raising the error at the end

> 
> " INFO:root:Checking configuration file.
> INFO:root:Welcome to AutoStatsQ - a station quality control checking tool.
> 
> INFO:Run: Number of stations: 9
> INFO:Catalog search:length catalog: 94
> INFO:Subset events: Plotting catalog azimuthal for full catalog: deep.
> INFO:root:saved ./results/catalog/catalog_global_Mgr7.0_2015-01-01-2021-12-01_deep.png
> INFO:Subset events: Plotting catalog histogram for full catalog: deep.
> Traceback (most recent call last):
>   File "/home/simone/anaconda3/envs/pyrocko/bin/autostatsq", line 33, in <module>
>     sys.exit(load_entry_point('autostatsq==0.1', 'console_scripts', 'autostatsq')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/autostatsq-0.1-py3.11.egg/autostatsq/network_control.py", line 401, in main
>     plot_catalog_hist(ev_cat, dist_array, mean_wedges_mp,
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/autostatsq-0.1-py3.11.egg/autostatsq/catalogplots.py", line 64, in plot_catalog_hist
>     ax1.hist(mean_wedges_mp, normed=False, bins=bins_hist, color='lightgrey')
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/matplotlib/__init__.py", line 1465, in inner
>     return func(ax, *map(sanitize_sequence, args), **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 7007, in hist
>     p._internal_update(kwargs)
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/matplotlib/artist.py", line 1219, in _internal_update
>     return self._update_props(
>            ^^^^^^^^^^^^^^^^^^^
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/matplotlib/artist.py", line 1193, in _update_props
>     raise AttributeError(
> AttributeError: Rectangle.set() got an unexpected keyword argument 'normed'  "
> 

The code generated only two files in the result folder that are:

catalog_global_Mgr7.0_2015-01-01-2021-12-01_deep.png
catalog_Mgr7.0.txt

but no one referred to shallow events. 
Do you know what is the problem and how to solve it?
Thanks,
Simone

**Comment by gesape** [comment]
Hi Simone,
I am afraid that is an error related to changes within matplotlib. The newer mpl version has different arguments in plotting histograms. I will hopefully soon have some time to change the code accordingly. In the meantime, you can simply set plot_hist_wedges to false in your config file and go ahead without plotting the histograms with the catalog statistics...

**Comment by bosby74** [comment]
Thank you Gesa,
 setting as false the plot_hist_wedges option, the code works fine...let me know about fixing the issue definitively
Ciao,
Simone

**Comment by bosby74** [comment]
Hi Gesa,
 I reopened this issue since the question is regarding the example procedure again.
In the Autoconfig file, I'm trying to set up my local data (in sds structure) and to set my response file, XML created via SMP portal but when I run 
autostatsq --config AutoStatsQ_settings.config --run -l INFO  
I get the error 

```
INFO:root:Checking configuration file.
WARNING:CONFIG: Set MetaDataDownloadConfig use_downmeta to true to use the downloaded metadata.
INFO:root:Welcome to AutoStatsQ - a station quality control checking tool.

INFO:Run: Number of stations: 5
INFO:Subset events: Subset of catalog for deep: 36 events.

INFO:Subset events: Subset of catalog for shallow: 45 events.

INFO:Restitution: Starting restitution of data.
Traceback (most recent call last):
  File "/home/simone/anaconda3/envs/pyrocko/bin/autostatsq", line 33, in <module>
    sys.exit(load_entry_point('autostatsq==0.1', 'console_scripts', 'autostatsq')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/autostatsq-0.1-py3.11.egg/autostatsq/network_control.py", line 824, in main
    responses.append(stationxml.load_xml(filename=file))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/pyrocko/guts.py", line 250, in g
    retval = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/pyrocko/guts.py", line 2346, in load_xml
    return _load_xml(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/pyrocko/guts.py", line 1940, in _load_xml
    return next(g)
           ^^^^^^^
```
The XML I want to load is created via SMP portal and it is in the SCML format.
Is there any particular information the XML should contain? or do you have any suggestion about the right format the XML should be or about its conversion from a classical SCML?
I didn't find any information in your manual pages about it so could be useful to understand what is the best format to be used...
Simone

**Comment by gesape** [comment]
Dear Simone, could you send me the entire station-xml file via email as well as your config file and the full error message? From the message above it is not possible for me to understand what the exact problem with the file is... My work email adress is listed on the front page of this git repo. Or if you are a member of the pyrocko hive community chat, you can also find me there as "gesa".

**Comment by mddalena** [comment]
> Hi, I've installed the AutoStatQ software and I'm trying to follow the step-by-step example in the instruction pdf. Following Step 1, regarding the Catalog generation, and running
> 
> autostatsq --config ./AutoStatsQ_settings.config --run -l INFO
> 
> I find this output raising the error at the end
> 
> > " INFO:root:Checking configuration file.
> > INFO:root:Welcome to AutoStatsQ - a station quality control checking tool.
> > INFO:Run: Number of stations: 9
> > INFO:Catalog search:length catalog: 94
> > INFO:Subset events: Plotting catalog azimuthal for full catalog: deep.
> > INFO:root:saved ./results/catalog/catalog_global_Mgr7.0_2015-01-01-2021-12-01_deep.png
> > INFO:Subset events: Plotting catalog histogram for full catalog: deep.
> > Traceback (most recent call last):
> > File "/home/simone/anaconda3/envs/pyrocko/bin/autostatsq", line 33, in 
> > sys.exit(load_entry_point('autostatsq==0.1', 'console_scripts', 'autostatsq')())
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/autostatsq-0.1-py3.11.egg/autostatsq/network_control.py", line 401, in main
> > plot_catalog_hist(ev_cat, dist_array, mean_wedges_mp,
> > File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/autostatsq-0.1-py3.11.egg/autostatsq/catalogplots.py", line 64, in plot_catalog_hist
> > ax1.hist(mean_wedges_mp, normed=False, bins=bins_hist, color='lightgrey')
> > File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/matplotlib/**init**.py", line 1465, in inner
> > return func(ax, *map(sanitize_sequence, args), **kwargs)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 7007, in hist
> > p._internal_update(kwargs)
> > File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/matplotlib/artist.py", line 1219, in _internal_update
> > return self._update_props(
> > ^^^^^^^^^^^^^^^^^^^
> > File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/matplotlib/artist.py", line 1193, in _update_props
> > raise AttributeError(
> > AttributeError: Rectangle.set() got an unexpected keyword argument 'normed'  "
> 
> The code generated only two files in the result folder that are:
> 
> catalog_global_Mgr7.0_2015-01-01-2021-12-01_deep.png catalog_Mgr7.0.txt
> 
> but no one referred to shallow events. Do you know what is the problem and how to solve it? Thanks, Simone

Hi, 
to solve this problem I deleted "normed=False" in catalogplots.py line 64. 
Path in your case is "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/autostatsq-0.1-py3.11.egg/autostatsq/catalogplots.py"

ax1.hist(mean_wedges_mp, bins=bins_hist, color='lightgrey')

Ciao,
Maddalena

**Comment by gesape** [comment]
> Hi Gesa, I reopened this issue since the question is regarding the example procedure again. In the Autoconfig file, I'm trying to set up my local data (in sds structure) and to set my response file, XML created via SMP portal but when I run autostatsq --config AutoStatsQ_settings.config --run -l INFO I get the error
> 
> ```
> INFO:root:Checking configuration file.
> WARNING:CONFIG: Set MetaDataDownloadConfig use_downmeta to true to use the downloaded metadata.
> INFO:root:Welcome to AutoStatsQ - a station quality control checking tool.
> 
> INFO:Run: Number of stations: 5
> INFO:Subset events: Subset of catalog for deep: 36 events.
> 
> INFO:Subset events: Subset of catalog for shallow: 45 events.
> 
> INFO:Restitution: Starting restitution of data.
> Traceback (most recent call last):
>   File "/home/simone/anaconda3/envs/pyrocko/bin/autostatsq", line 33, in <module>
>     sys.exit(load_entry_point('autostatsq==0.1', 'console_scripts', 'autostatsq')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/autostatsq-0.1-py3.11.egg/autostatsq/network_control.py", line 824, in main
>     responses.append(stationxml.load_xml(filename=file))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/pyrocko/guts.py", line 250, in g
>     retval = f(*args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/pyrocko/guts.py", line 2346, in load_xml
>     return _load_xml(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/simone/anaconda3/envs/pyrocko/lib/python3.11/site-packages/pyrocko/guts.py", line 1940, in _load_xml
>     return next(g)
>            ^^^^^^^
> ```
> 
> The XML I want to load is created via SMP portal and it is in the SCML format. Is there any particular information the XML should contain? or do you have any suggestion about the right format the XML should be or about its conversion from a classical SCML? I didn't find any information in your manual pages about it so could be useful to understand what is the best format to be used... Simone



Dear Simone,
I am sorry for the delayed response. Unfortunately AutoStatsQ does not support SeisComps SCML format, it can only handle the station-xml format that is used by FDSN etc. We should probably add the functionality. But for now it would be best if you convert to stationxml format (e.g., see here for a converter: https://www.seiscomp.de/doc/apps/import_inv.html).
Best regards,
Gesa
