### ISSUE TITLE
Data request exception error

### ISSUE THREAD

**Issue by ifountoul** [gesape/AutoStatsQ#7]
Hello!
Very often and in many stations I am facing an exception error when i am trying to download data in order to use AutostatsQ. After scouting to understand the problem, i found out that in these cases Pyrocko displays time_out error.

I solved it adding to network_control.py file: `fdsn.g_timeout = 60.`

Raising the timeout time, will be very helpful in order to avoid exceptions due to slow interactions with the Data Nodes.
Maybe will be useful to add this option to AutostatsQ config file in the future.

Thank you.

**Comment by gesape** [comment]
Thanks and sorry for the very late reply! It is now added, as suggested...
